name: Build & Release Dist

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: Build and release dist
    runs-on: ubuntu-latest
    permissions:
      contents: write # required to create releases / push tags
      packages: write
      issues: none
      pull-requests: none

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full history in case you want tags or version derivation

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Verify dist exists
        run: |
          if [ ! -d dist ]; then
            echo "dist/ folder not found, build failed"
            exit 1
          fi

      - name: Zip dist folder
        run: |
          ZIP_NAME="dist-$(date +'%Y%m%dT%H%M%SZ')-$(git rev-parse --short HEAD).zip"
          zip -r "$ZIP_NAME" dist
          echo "zip_name=$ZIP_NAME" >>"$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
          name: Release build-$(date +'%Y%m%d')-$(git rev-parse --short HEAD)
          body: Automated build release
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Upload dist zip to release
        uses: softprops/action-gh-release@v2
        if: steps.create_release.outputs.upload_url != ''
        with:
          tag_name: ${{ steps.create_release.outputs.tag_name }}
          name: ${{ steps.create_release.outputs.name }}
          files: ${{ steps.build-and-release.outputs.zip_name || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
